# Each new term in the Fibonacci sequence is generated by adding the previous 
# two terms. By starting with 1 and 2, the first 10 terms will be:
# 1, 2, 3, 5, 8, 13, 21, 34, 55, 89, ...
# By considering the terms in the Fibonacci sequence whose values do not exceed
# four million, find the sum of the even-valued terms.
previous_term = 1
previous_previous_term = 0
current_term = 0
even_sum = 0

while previous_term + previous_previous_term <= 4000000:
    current_term = previous_term + previous_previous_term
    previous_previous_term = previous_term
    previous_term = current_term

    if current_term % 2 == 0:
        even_sum += current_term
print('The total sum of even terms is : ' + str(even_sum))
